services:
  docs:
    image: green_cart_api_local_docs
    container_name: green_cart_api_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./green_cart_api:/app/green_cart_api:z
    ports:
      - '9000:9000'
    command: /start-docs
